name: Deploy to GitHub Pages

permissions:
  contents: write     # allow commit/push to gh-pages
  pages: write        # not strictly required, but fine

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci --legacy-peer-deps

      - name: Create .env for Vite
        run: |
          echo "VITE_CONTACT_SERVICE_ID=${{ secrets.VITE_CONTACT_SERVICE_ID }}"   >> .env
          echo "VITE_CONTACT_TEMPLATE_ID=${{ secrets.VITE_CONTACT_TEMPLATE_ID }}" >> .env
          echo "VITE_CONTACT_PUBLIC_KEY=${{ secrets.VITE_CONTACT_PUBLIC_KEY }}"   >> .env

      - name: Bump build hash
        run: |
          echo "build=$(date +%s)" > src/_build.txt

      - run: npm run build

      - uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true
          allow_empty_commit: true